# Generated by Django 4.2.7 on 2023-11-01 15:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customuser", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="createuser",
            name="phone",
            field=models.CharField(
                max_length=12,
                validators=[django.core.validators.RegexValidator("^+7[d]$")],
            ),
        ),
    ]
