# Generated by Django 4.2.7 on 2023-11-03 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customuser", "0003_alter_createuser_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="createuser",
            name="age",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="createuser",
            name="text",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
