# Generated by Django 4.2.7 on 2023-11-03 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customuser", "0004_createuser_age_createuser_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="createuser",
            name="cloth_color",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
