# Generated by Django 4.2.7 on 2023-11-03 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customuser", "0005_createuser_cloth_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="createuser",
            name="age",
            field=models.IntegerField(null=True),
        ),
    ]
